[package]
name = "yew-blog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gloo-net = "0.2.3"
serde = { version = "1.0.143", features = ["derive"] }
wasm-bindgen-futures = "0.4.32"
yew = "0.19.3"
